import Foundation
import AVFoundation
import TonearmWatchCore
import TonearmWatchProtocol

/// DEBUG-only deterministic seed for the watch UI smoke test. Copies the bundled CC0 ocean AAC
/// generated by PhoneWatchAudioPreparation on the host; the watch never transcodes it.
/// through the real audio installer using an extensionless cache blob delivered before its
/// metadata, then builds the playlists the smoke test browses. No network or WCSession transfer.
enum WatchFixtureSeeder {
    static let trackID = "fixture-ambient-ocean"
    static let trackTitle = "ambient-ocean"
    static let fixtureName = "ambient-ocean-watch-aac128"

    static func seed(repository: WatchLibraryRepository, audioDirectory: URL) async {
        guard let source = bundledOceanURL() else {
            NSLog("WatchFixtureSeeder: AAC128 fixture not found in bundle")
            return
        }
        let fm = FileManager.default
        let staged = fm.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        defer { try? fm.removeItem(at: staged) }
        do {
            try fm.createDirectory(at: staged, withIntermediateDirectories: true)
            let file = try AVAudioFile(forReading: source)
            guard file.fileFormat.streamDescription.pointee.mFormatID == kAudioFormatMPEG4AAC else {
                throw CocoaError(.fileReadCorruptFile)
            }
            let incoming = staged.appendingPathComponent(String(repeating: "a", count: 64) + "-m4a")
            try fm.copyItem(at: source, to: incoming)
            let measured = try WatchFileDigest.measure(incoming)
            let installer = WatchFileInstaller(repository: repository, audioDirectory: audioDirectory,
                stagingDirectory: staged.appendingPathComponent("deferred"))
            _ = await installer.install(stagedURL: incoming, metadata: WatchAudioFileMetadata(
                trackID: WatchTrackID(trackID), expectedBytes: measured.bytes, sha256: measured.sha256,
                fileExtension: WatchAudioFileMetadata.fileExtension(for: incoming)).dictionary)
            try await repository.upsertTrack(.init(
                trackID: trackID, title: trackTitle, artist: "Nox_Sound · CC0", albumTitle: "Built-in Sounds"))
            _ = await installer.retryDeferred()
            try await repository.upsertPlaylist(
                .init(playlistID: "fixture-builtin", title: "Built-in Playlist", trackIDs: [trackID]),
                desiredOnWatch: true)
            try await repository.upsertPlaylist(
                .init(playlistID: "fixture-pinned", title: "Pinned Track Smoke", trackIDs: [trackID]),
                desiredOnWatch: true)
        } catch {
            NSLog("WatchFixtureSeeder: seeding failed: \(error)")
        }
    }

    /// The bundled WAV lives in the `TonearmCore` SPM resource bundle nested inside the watch app
    /// (`TonearmCore_TonearmCore.bundle/Audio/`), not at the main-bundle root — so a plain
    /// `Bundle.main.url(forResource:)` misses it. Search the main bundle, then every nested `.bundle`.
    private static func bundledOceanURL() -> URL? {
        let fm = FileManager.default
        for bundle in [Bundle.main] + nestedBundles(in: Bundle.main) {
            if let url = bundle.url(forResource: fixtureName, withExtension: "m4a") { return url }
            if let url = bundle.url(forResource: fixtureName, withExtension: "m4a", subdirectory: "Audio") {
                return url
            }
        }
        // Last resort: a direct filesystem walk of the app bundle.
        if let enumerator = fm.enumerator(at: Bundle.main.bundleURL,
                                          includingPropertiesForKeys: nil) {
            for case let url as URL in enumerator where url.lastPathComponent == "\(fixtureName).m4a" {
                return url
            }
        }
        return nil
    }

    private static func nestedBundles(in bundle: Bundle) -> [Bundle] {
        let contents = (try? FileManager.default.contentsOfDirectory(
            at: bundle.bundleURL, includingPropertiesForKeys: nil)) ?? []
        return contents.filter { $0.pathExtension == "bundle" }.compactMap(Bundle.init(url:))
    }
}
