// SPDX-License-Identifier: GPL-3.0-or-later
//
// Tonearm (Platterhead DJ) — Copyright (C) 2026 John Arley Burns.
// See ../../LICENSE.

#if canImport(UIKit) && !os(watchOS)
import Foundation
import TonearmDiscovery
import UIKit

/// Resolves the converted CLAP audio + text encoders and their bundled
/// sidecars for the Discovery indexing/search pipeline, the same way the DJ
/// semantic stack delivers Core ML resources (IMPLEMENT_CLAP_PLAN.md §8):
///
///  - the ~137 MB `CLAPAudioEncoder` package is an On-Demand Resource, tag
///    `clap-audio`; the `CLAPTextEncoder` package is ODR tag `clap-text`
///    (`Config/models-odr.yml`, generated by `scripts/generate-project.sh`
///    from what is on the build host). Xcode compiles each `.mlpackage` to a
///    `.mlmodelc` inside the asset pack; ODR content is mounted into the main
///    bundle's resource directory once `beginAccessingResources` succeeds.
///  - `mel_filterbank_slaney_64.bin` (audio frontend) and the RoBERTa
///    `vocab.json` / `merges.txt` (text tokenizer) ship bundled in
///    `Resources/CLAP/`.
///
/// When the ODR pack has not been fetched (or the tag is absent from a build
/// with no converted package on the host), `currentResources()` returns
/// `.unavailable` and every index job parks at `waitingForModel` — never a
/// fabricated embedding (plan §8).
final class DiscoveryModelResources: @unchecked Sendable {
    static let shared = DiscoveryModelResources()

    /// Must match the tags in `Config/models-odr.yml` / `ModelTag`.
    private static let audioTag = "clap-audio"
    private static let textTag = "clap-text"

    private let audioRequest = NSBundleResourceRequest(tags: [DiscoveryModelResources.audioTag])
    private let textRequest = NSBundleResourceRequest(tags: [DiscoveryModelResources.textTag])
    private let lock = NSLock()
    private var didBeginAccessing = false

    /// Ask iOS to make the `clap-audio` ODR pack available. Best-effort and
    /// idempotent; a failure (no such tag, no network on first fetch) simply
    /// leaves `currentResources()` returning `.unavailable`, which is the
    /// honest `waitingForModel` path, never an error dialog (FR-SEM-6 / §8).
    func beginAccessing() {
        lock.lock()
        let already = didBeginAccessing
        didBeginAccessing = true
        lock.unlock()
        guard !already else { return }

        for (tag, request) in [(Self.audioTag, audioRequest), (Self.textTag, textRequest)] {
            request.loadingPriority = NSBundleResourceRequestLoadingPriorityUrgent
            request.beginAccessingResources { error in
                if let error {
                    NSLog("[Discovery] \(tag) ODR not available: \(error.localizedDescription)")
                }
            }
        }
    }

    /// Synchronously resolve whatever is on disk right now — safe to hand to
    /// `ModelManager`'s `@Sendable () -> Resources` provider.
    func currentResources() -> ModelManager.Resources {
        var directories: [URL] = []
        if let resourceURL = Bundle.main.resourceURL {
            directories.append(resourceURL)
        }
        return ModelResourceLocator(searchDirectories: directories).resolve()
    }

    /// Real bytes off `NSBundleResourceRequest.progress` for whichever tag(s)
    /// are actually still fetching — never a fabricated fraction (CLAUDE.md
    /// "no silent/magic background work": a `waitingForModel` state with no
    /// size is indistinguishable from stuck). `nil` before a real download
    /// has started (the system hasn't reported a byte count yet) or once
    /// every in-flight request has finished — safe to hand to
    /// `DiscoveryAssembly`'s `@Sendable () -> ModelDownloadProgress?`
    /// provider.
    func currentDownloadProgress() -> ModelDownloadProgress? {
        var completed: Int64 = 0
        var total: Int64 = 0
        var anyInFlight = false
        for request in [audioRequest, textRequest] {
            let progress = request.progress
            guard progress.totalUnitCount > 0 else { continue }
            completed += progress.completedUnitCount
            total += progress.totalUnitCount
            if !progress.isFinished { anyInFlight = true }
        }
        guard total > 0, anyInFlight else { return nil }
        return ModelDownloadProgress(completedBytes: completed, totalBytes: total)
    }
}
#endif
