// SPDX-License-Identifier: GPL-3.0-or-later
//
// Tonearm (Platterhead DJ) — Copyright (C) 2026 John Arley Burns.
// See ../../LICENSE.

#if !os(watchOS)
import Foundation
import TonearmDiscovery

/// Resolves the converted CLAP audio + text encoders and their bundled
/// sidecars for the Discovery indexing/search pipeline, the same way the DJ
/// semantic stack delivers Core ML resources (IMPLEMENT_CLAP_PLAN.md §8):
///
///  - the ~123 MB `CLAPAudioEncoder` package is an On-Demand Resource, tag
///    `clap-audio`; the ~221 MB `CLAPTextEncoder` package is ODR tag
///    `clap-text` — both real CoreML packages of comparable size, not a
///    small sidecar (`Config/models-odr.yml`, generated by
///    `scripts/generate-project.sh` from what is on the build host). Xcode
///    compiles each `.mlpackage` to a `.mlmodelc` inside the asset pack;
///    ODR content is mounted into the main bundle's resource directory once
///    `beginAccessingResources` succeeds. Combined, this is a ~344 MB
///    one-time fetch — on a slow connection, or if iOS is deferring it
///    pending Wi-Fi (Settings → Cellular → per-app "Automatic Downloads"),
///    genuinely taking a long time looks identical to being stuck; there is
///    no public API to tell "slow" apart from "iOS is waiting for Wi-Fi"
///    for On-Demand Resources.
///  - `mel_filterbank_slaney_64.bin` (audio frontend) and the RoBERTa
///    `vocab.json` / `merges.txt` (text tokenizer) ship bundled in
///    `Resources/CLAP/`.
///
/// When the ODR pack has not been fetched (or the tag is absent from a build
/// with no converted package on the host), `currentResources()` returns
/// `.unavailable` and every index job parks at `waitingForModel` — never a
/// fabricated embedding (plan §8).
final class DiscoveryModelResources: @unchecked Sendable {
    static let shared = DiscoveryModelResources()

    /// Must match the tags in `Config/models-odr.yml` / `ModelTag`.
    private static let audioTag = "clap-audio"
    private static let textTag = "clap-text"

    #if os(macOS)
    // `NSBundleResourceRequest`/On-Demand Resources don't exist on macOS at
    // all (native-mac-app-plan.md §2c/§4 — not enumerated by the plan's own
    // porting survey, found during this build). `currentResources()` below
    // still resolves whatever's genuinely present in the app bundle; there
    // is simply no ODR-download flow to drive on this platform, so every
    // other method here is an honest, static "nothing to report" rather
    // than a fabricated one (CLAUDE.md "no silent/magic background work").
    func currentDownloadError() -> String? { nil }
    func beginAccessing() {}
    func currentDownloadProgress() -> ModelDownloadProgress? { nil }
    func currentPerTagDebugSummary() -> String { "not applicable on macOS (no On-Demand Resources)" }

    func currentResources() -> ModelManager.Resources {
        var directories: [URL] = []
        if let resourceURL = Bundle.main.resourceURL {
            directories.append(resourceURL)
        }
        return ModelResourceLocator(searchDirectories: directories, bundle: Bundle.main).resolve()
    }

    func currentDiagnosticsDetail() -> ModelDiagnosticsDetail {
        let resources = currentResources()
        let artifacts = [
            ModelDiagnosticsDetail.Artifact(
                name: "Audio encoder", isResolved: resources.audioEncoderURL != nil,
                resolvedName: resources.audioEncoderURL?.lastPathComponent),
            ModelDiagnosticsDetail.Artifact(
                name: "Text encoder", isResolved: resources.textEncoderURL != nil,
                resolvedName: resources.textEncoderURL?.lastPathComponent),
            ModelDiagnosticsDetail.Artifact(
                name: "Mel filterbank", isResolved: resources.melFilterBankURL != nil,
                resolvedName: resources.melFilterBankURL?.lastPathComponent),
            ModelDiagnosticsDetail.Artifact(
                name: "Tokenizer vocab", isResolved: resources.tokenizerVocabURL != nil,
                resolvedName: resources.tokenizerVocabURL?.lastPathComponent),
            ModelDiagnosticsDetail.Artifact(
                name: "Tokenizer merges", isResolved: resources.tokenizerMergesURL != nil,
                resolvedName: resources.tokenizerMergesURL?.lastPathComponent),
        ]
        return ModelDiagnosticsDetail(downloadTags: [], artifacts: artifacts, downloadError: nil)
    }
    #else

    /// Per-tag retry/error bookkeeping, including the live
    /// `NSBundleResourceRequest` (`var`, not `let`: a real device crashed
    /// with `NSInvalidArgumentException` "beginAccessingResources was
    /// called more than once or at the wrong time" — Apple does not
    /// support calling `beginAccessingResources` again on the same
    /// instance, which the original retry logic did; `startRequest(tag:
    /// state:)` now creates a brand-new instance for every attempt,
    /// including the first, so this invariant holds unconditionally).
    /// This used to be ONE shared
    /// `lastError`/`retryDelay`/`retryWorkItem` for both tags — a real
    /// device showed why that's wrong: `clap-audio` failed every ~5s
    /// forever (a genuinely broken local-install case) while `clap-text`
    /// happened to succeed on every attempt, and text's success handler
    /// unconditionally reset the SHARED `retryDelay` to 5 and `lastError`
    /// to `nil` — permanently defeating audio's exponential backoff
    /// (observed hammering the same failure every ~5.5s for 7+ minutes
    /// instead of 5→10→20→...→300) and letting a real, persistent error be
    /// silently wiped by an unrelated tag's success. Each tag now owns its
    /// own state, so one tag's outcome can never affect the other's.
    private final class TagState {
        var request: NSBundleResourceRequest
        var lastError: String?
        var retryDelay: TimeInterval = 5
        var retryWorkItem: DispatchWorkItem?
        init(tag: String) { request = NSBundleResourceRequest(tags: [tag]) }
    }

    private let lock = NSLock()
    private var didBeginAccessing = false
    private lazy var audioState = TagState(tag: Self.audioTag)
    private lazy var textState = TagState(tag: Self.textTag)

    private func states() -> [(String, TagState)] {
        [(Self.audioTag, audioState), (Self.textTag, textState)]
    }

    /// The most recent `beginAccessingResources` failure(s), if any —
    /// surfaced through diagnostics and the status UI so a stalled/failed
    /// ODR fetch (e.g. `NSBundleResourceRequestLowDiskSpaceKey`,
    /// `NSBundleResourceRequestUnknownResourceIdentifierError`, or a plain
    /// network error) is never invisible (CLAUDE.md "no silent/magic
    /// background work"). Joins both tags' errors when both have one, so
    /// neither is silently hidden behind the other; `nil` once every tag
    /// with an error has retried successfully.
    func currentDownloadError() -> String? {
        lock.lock()
        defer { lock.unlock() }
        let errors = states().compactMap(\.1.lastError)
        return errors.isEmpty ? nil : errors.joined(separator: "; ")
    }

    /// Ask iOS to make the `clap-audio`/`clap-text` ODR packs available.
    /// Best-effort; a failure (no such tag, no network on first fetch, low
    /// disk space) is captured in `currentDownloadError()` — never just an
    /// `NSLog` line invisible to both the user and support — and retried
    /// with backoff, independently per tag, rather than left to park at
    /// `waitingForModel` forever (FR-SEM-6 / §8: honest, but not silently
    /// stuck).
    func beginAccessing() {
        lock.lock()
        let already = didBeginAccessing
        didBeginAccessing = true
        lock.unlock()
        guard !already else { return }
        for (tag, state) in states() {
            startRequest(tag: tag, state: state)
        }
    }

    private func startRequest(tag: String, state: TagState) {
        // A fresh instance every attempt, including the first — see
        // `TagState`'s doc: reusing one across a retry crashed the app
        // (`NSInvalidArgumentException`, "beginAccessingResources was
        // called more than once or at the wrong time").
        let fresh = NSBundleResourceRequest(tags: [tag])
        lock.lock()
        state.request = fresh
        lock.unlock()

        fresh.loadingPriority = NSBundleResourceRequestLoadingPriorityUrgent
        fresh.beginAccessingResources { [weak self] error in
            guard let self else { return }
            if let error {
                let nsError = error as NSError
                let message = "\(tag): \(nsError.localizedDescription) (code \(nsError.code))"
                guard Self.isRetryable(nsError) else {
                    // NSBundleOnDemandResourceInvalidParameterError (4994):
                    // there is no real ODR host to fetch this tag from at
                    // all — true of every local development-signed install,
                    // since On-Demand Resources only actually download
                    // through TestFlight/App Store distribution. This is
                    // not a real, actionable error for the user (it can
                    // never happen on a distributed build, and retrying it
                    // locally can never succeed either) — never surface it
                    // as lastError/diagnostics, never retry it, log it once
                    // for a developer reading the console and stop. This is
                    // the one specific, narrow case CLAUDE.md's "no silent
                    // magic" doesn't apply to: it is guaranteed environment
                    // noise, not a real condition to explain to the user.
                    NSLog("[Discovery] ODR unavailable in this build (not TestFlight/App Store), not retrying: \(message)")
                    return
                }
                NSLog("[Discovery] ODR not available: \(message)")
                self.lock.lock()
                state.lastError = message
                let delay = state.retryDelay
                state.retryDelay = min(state.retryDelay * 2, 300)
                self.lock.unlock()
                self.scheduleRetry(tag: tag, state: state, after: delay)
            } else {
                self.lock.lock()
                state.lastError = nil
                state.retryDelay = 5
                self.lock.unlock()
            }
        }
    }

    /// `NSBundleOnDemandResourceInvalidParameterError` (4994) means the ODR
    /// system has no real host to fetch this tag from at all — true of
    /// every local development-signed install, since On-Demand Resources
    /// only actually download through TestFlight/App Store distribution.
    /// Every other documented ODR error (out-of-space, exceeded-max-size,
    /// unknown-resource, a plain network failure) is at least plausibly
    /// transient and worth retrying.
    private static func isRetryable(_ error: NSError) -> Bool {
        error.code != 4994
    }

    /// Snapshot of the two live requests, lock-protected since `startRequest`
    /// can replace one from a retry's background-queue callback while a
    /// diagnostics read is in flight on another thread.
    private func currentRequests() -> [(String, NSBundleResourceRequest)] {
        lock.lock()
        defer { lock.unlock() }
        return states().map { tag, state in (tag, state.request) }
    }

    /// A failed `beginAccessingResources` call does not retry on its own —
    /// without this, a transient failure (e.g. no network at launch) would
    /// leave the app parked at `waitingForModel` indefinitely even once
    /// connectivity returns, with no user action able to fix it (the "0%
    /// downloaded... then it disappeared" report this guards against).
    /// Scoped per tag (`state.retryWorkItem`, not a shared one) so
    /// `clap-audio` retrying does not cancel `clap-text`'s independent
    /// retry schedule or vice versa.
    private func scheduleRetry(tag: String, state: TagState, after delay: TimeInterval) {
        lock.lock()
        state.retryWorkItem?.cancel()
        let item = DispatchWorkItem { [weak self] in self?.startRequest(tag: tag, state: state) }
        state.retryWorkItem = item
        lock.unlock()
        DispatchQueue.main.asyncAfter(deadline: .now() + delay, execute: item)
    }

    /// Synchronously resolve whatever is on disk right now — safe to hand to
    /// `ModelManager`'s `@Sendable () -> Resources` provider. Passes
    /// `Bundle.main` so ODR-mounted content actually resolves — its
    /// on-disk location is a hashed, unpredictable asset-pack directory
    /// (see `ModelResourceLocator.bundle`'s doc), not a guessable child of
    /// `resourceURL`; `searchDirectories` alone was never sufficient for
    /// real On-Demand Resource content, only for the dev-checkout/test
    /// case where resources sit in a plain folder.
    func currentResources() -> ModelManager.Resources {
        var directories: [URL] = []
        if let resourceURL = Bundle.main.resourceURL {
            directories.append(resourceURL)
        }
        return ModelResourceLocator(searchDirectories: directories, bundle: Bundle.main).resolve()
    }

    /// Real bytes off `NSBundleResourceRequest.progress` for both tags —
    /// never a fabricated fraction (CLAUDE.md "no silent/magic background
    /// work": a `waitingForModel` state with no size is indistinguishable
    /// from stuck). `nil` only before either tag has reported any byte
    /// count at all. The actual summing happens in
    /// `ModelDownloadProgress.aggregate(_:)` (`Sources/Discovery/`) — kept
    /// out of this Xcode-only file specifically so it's covered by
    /// `swift test`; this method's only job is turning the two live
    /// `NSBundleResourceRequest.progress` objects into plain samples.
    func currentDownloadProgress() -> ModelDownloadProgress? {
        ModelDownloadProgress.aggregate(perTagSamples().map(\.1))
    }

    /// Per-tag byte counts for the diagnostics export — the combined
    /// `currentDownloadProgress()` number can't tell "one tag finished
    /// while the other is genuinely stuck at zero" apart from "both
    /// progressing normally" (real report: a small `clap-text` finished
    /// while the ~137 MB `clap-audio` never reported any bytes at all,
    /// which the combined number alone rendered as a nonsensical "0 of 0
    /// MB (100%)"). This is what lets a diagnostics export say exactly
    /// which tag is the one not moving, instead of one ambiguous blend.
    func currentPerTagDebugSummary() -> String {
        perTagSamples()
            .map { tag, sample in
                let state = sample.isFinished ? "finished" : (sample.totalBytes > 0 ? "in progress" : "not started")
                return "\(tag): \(sample.completedBytes)/\(sample.totalBytes) bytes (\(state))"
            }
            .joined(separator: "; ")
    }

    private func perTagSamples() -> [(String, ModelDownloadProgress.RequestSample)] {
        currentRequests().map { tag, request in
            (tag, ModelDownloadProgress.RequestSample(
                completedBytes: request.progress.completedUnitCount,
                totalBytes: request.progress.totalUnitCount,
                isFinished: request.progress.isFinished))
        }
    }

    /// The full structured breakdown for the Sound Index screen's "Models"
    /// section — both the raw ODR download state (`DownloadTag`, from the
    /// live `NSBundleResourceRequest`s) AND, separately, whether each
    /// required on-disk artefact actually resolves right now via
    /// `ModelResourceLocator`. These are two different facts that a real
    /// device diagnostics export once showed disagreeing (both tags
    /// "finished" downloading while `modelResourceAvailable` stayed false)
    /// — this view is what makes that gap directly visible instead of
    /// requiring a diagnostics-export round-trip to discover it again.
    func currentDiagnosticsDetail() -> ModelDiagnosticsDetail {
        let tags = perTagSamples().map { tag, sample in
            ModelDiagnosticsDetail.DownloadTag(
                tag: tag, completedBytes: sample.completedBytes,
                totalBytes: sample.totalBytes, isFinished: sample.isFinished)
        }
        let resources = currentResources()
        let artifacts = [
            ModelDiagnosticsDetail.Artifact(
                name: "Audio encoder", isResolved: resources.audioEncoderURL != nil,
                resolvedName: resources.audioEncoderURL?.lastPathComponent),
            ModelDiagnosticsDetail.Artifact(
                name: "Text encoder", isResolved: resources.textEncoderURL != nil,
                resolvedName: resources.textEncoderURL?.lastPathComponent),
            ModelDiagnosticsDetail.Artifact(
                name: "Mel filterbank", isResolved: resources.melFilterBankURL != nil,
                resolvedName: resources.melFilterBankURL?.lastPathComponent),
            ModelDiagnosticsDetail.Artifact(
                name: "Tokenizer vocab", isResolved: resources.tokenizerVocabURL != nil,
                resolvedName: resources.tokenizerVocabURL?.lastPathComponent),
            ModelDiagnosticsDetail.Artifact(
                name: "Tokenizer merges", isResolved: resources.tokenizerMergesURL != nil,
                resolvedName: resources.tokenizerMergesURL?.lastPathComponent),
        ]
        return ModelDiagnosticsDetail(
            downloadTags: tags, artifacts: artifacts, downloadError: currentDownloadError())
    }
    #endif
}
#endif
