#if !os(watchOS)
import CoreML
import Foundation

/// Turns a raw `.mlpackage` into a URL `MLModel(contentsOf:)` can actually load.
///
/// `Config/models-odr.yml` adds `CLAPAudioEncoder.mlpackage` / `CLAPTextEncoder.mlpackage` /
/// `DemucsStems.mlpackage` to the Xcode project as `type: folder` (a plain folder reference,
/// generated by `scripts/generate-project.sh` — see that file and `project.yml`). A folder
/// reference is copied into the app/ODR asset pack byte-for-byte; it never gets Xcode's Core ML
/// build rule, so the `.mlmodelc` `ModelResourceLocator` prefers never exists on a real device —
/// only the raw `.mlpackage` does. Passing that straight to `MLModel(contentsOf:)` throws
/// "Compile the model with Xcode or 'MLModel.compileModel(at:)'" (confirmed from a real device's
/// Sound Index failures), because that call only ever accepts an already-compiled model.
///
/// This compiles the package once, on first use, into a durable cache in Application Support, and
/// reuses the compiled copy on every later launch instead of recompiling a 100+ MB package every
/// time. A `.mlmodelc` resolved directly (a bare SwiftPM/dev checkout, or if the build ever does
/// start compiling these) passes through unchanged — there is nothing to do.
public enum CompiledModelCache {
    public enum CacheError: Error, LocalizedError, Equatable {
        case compileFailed(String)

        public var errorDescription: String? {
            switch self {
            case .compileFailed(let detail):
                return "Could not compile the model: \(detail)"
            }
        }
    }

    /// A URL safe to hand to `MLModel(contentsOf:)`. Compiles and caches on first call for a
    /// given package; later calls for the same, unchanged package are a cheap on-disk check.
    public static func loadableURL(for packageURL: URL,
                                   fileManager: FileManager = .default) throws -> URL {
        guard packageURL.pathExtension.lowercased() == "mlpackage" else { return packageURL }

        let compiledURL = cacheLocation(for: packageURL, fileManager: fileManager)
        if isFresh(compiledURL, comparedTo: packageURL, fileManager: fileManager) {
            return compiledURL
        }

        do {
            let freshlyCompiled = try MLModel.compileModel(at: packageURL)
            try fileManager.createDirectory(at: compiledURL.deletingLastPathComponent(),
                                            withIntermediateDirectories: true)
            if fileManager.fileExists(atPath: compiledURL.path) {
                try fileManager.removeItem(at: compiledURL)
            }
            try fileManager.moveItem(at: freshlyCompiled, to: compiledURL)
            return compiledURL
        } catch let error as CacheError {
            throw error
        } catch {
            throw CacheError.compileFailed(error.localizedDescription)
        }
    }

    private static func cacheLocation(for packageURL: URL, fileManager: FileManager) -> URL {
        let base = (try? fileManager.url(for: .applicationSupportDirectory, in: .userDomainMask,
                                         appropriateFor: nil, create: true))
            ?? fileManager.temporaryDirectory
        let name = packageURL.deletingPathExtension().lastPathComponent
        return base.appendingPathComponent("CompiledModels", isDirectory: true)
            .appendingPathComponent(name).appendingPathExtension("mlmodelc")
    }

    /// The cached compile is reusable when it exists and is no older than the source package —
    /// a fresh app build (a new ODR asset pack, or a converted model with an updated
    /// `Config/models.lock` entry) always carries a newer copy of the package than any previous
    /// install's cache, so this recompiles exactly when the source actually changed.
    private static func isFresh(_ compiledURL: URL, comparedTo packageURL: URL,
                                fileManager: FileManager) -> Bool {
        guard let compiledDate = modificationDate(compiledURL, fileManager: fileManager),
              let sourceDate = modificationDate(packageURL, fileManager: fileManager)
        else { return false }
        return compiledDate >= sourceDate
    }

    private static func modificationDate(_ url: URL, fileManager: FileManager) -> Date? {
        (try? fileManager.attributesOfItem(atPath: url.path))?[.modificationDate] as? Date
    }
}
#endif
