#!/bin/bash
# Generate Tonearm.xcodeproj — `make project`.
#
# This wraps `xcodegen generate` with exactly one decision: does the converted
# stems model exist on this machine?
#
#   Resources/Models/DemucsStems.mlpackage  present → the ODR tag is in the project
#                                           absent  → it is not, and stems report
#                                                     themselves unavailable (§36.5)
#
# WHY THIS EXISTS. The model is 210 MB of FP32 weights, converted by
# `tools/demucs-coreml/` and gitignored like every other build product (plan
# dj-stems-model S6). A clean checkout does not have it — and a clean checkout is
# what CI builds from. Listing it unconditionally in project.yml made
# `xcodegen generate` fail outright ("Target Tonearm has a missing source
# directory"); marking it `optional: true` got past validation and then failed the
# build instead, copying a file that is not there into the asset pack:
#
#   CpResource .../demucs-stems-<hash>.assetpack/DemucsStems.mlpackage
#   ** BUILD FAILED **
#
# Either way the TestFlight job dies before it archives, so the first push would
# have produced no build at all. The overlay this script writes is the fix: the
# entry exists when the file does.
#
# It is safe to run at any time and safe to run in CI: the overlay is rewritten
# from the filesystem on every run, so a stems-enabled overlay committed by
# accident cannot leak into a build that has no model to back it.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

MODEL="Resources/Models/DemucsStems.mlpackage"
OVERLAY="Config/stems-odr.yml"

if [[ -d "$MODEL" ]]; then
  cat > "$OVERLAY" <<'YAML'
# GENERATED by scripts/generate-project.sh — do not edit, and do not commit this
# form: it is the "model present on this machine" overlay. The committed form is
# the empty one (see the script).
targets:
  Tonearm:
    sources:
      - path: Resources/Models/DemucsStems.mlpackage
        type: folder
        buildPhase: resources
        resourceTags:
          - demucs-stems
YAML
  echo "==> stems: $MODEL found — the demucs-stems ODR tag is in this project"
else
  cat > "$OVERLAY" <<'YAML'
# GENERATED by scripts/generate-project.sh — do not edit.
#
# The empty overlay: no converted stems model on this machine, so the
# demucs-stems ODR tag is not in the project. Stems then report themselves
# unavailable through the already-tested honest-absence path (§36.5, FR-SEM-6) —
# decks play the full mix and the stem faders stay disabled.
#
# This is the committed form, and the form CI generates.
targets: {}
YAML
  echo "==> stems: no $MODEL — building without the demucs-stems ODR tag."
  echo "    Stems will report themselves unavailable (§36.5). Convert the model with"
  echo "    tools/demucs-coreml/ and re-run to include it."
fi

xcodegen generate
