#!/bin/bash
# Generate Tonearm.xcodeproj — `make project`.
#
# This wraps `xcodegen generate` with exactly one decision, taken per model:
# is that converted Core ML package on this machine?
#
#   Resources/Models/CLAPAudioEncoder.mlpackage  present → its ODR tag is in the
#   Resources/Models/CLAPTextEncoder.mlpackage            project
#   Resources/Models/DemucsStems.mlpackage       absent  → it is not, and the
#                                                         feature reports itself
#                                                         unavailable (§36.5,
#                                                         FR-SEM-6)
#
# WHY THIS EXISTS. None of the three packages is in the repository. Demucs is
# 210 MB of FP32 weights, gitignored like every other build product (plan
# dj-stems-model S6); the two CLAP encoders were committed until 2026-08-17,
# when GitHub rejected the first push of the DJ work for exceeding its 100 MB
# file limit, and they became release assets (Config/models.lock,
# scripts/fetch-models.sh). So a checkout does not have them until something
# fetches them — and a clean checkout is what CI builds from.
#
# Listing a missing package unconditionally in project.yml made `xcodegen
# generate` fail outright ("Target Tonearm has a missing source directory");
# marking it `optional: true` got past validation and then failed the build
# instead, copying a file that is not there into the asset pack:
#
#   CpResource .../demucs-stems-<hash>.assetpack/DemucsStems.mlpackage
#   ** BUILD FAILED **
#
# Either way the TestFlight job dies before it archives, so the first push would
# have produced no build at all. The overlay this script writes is the fix: the
# entry exists when the directory does.
#
# It is safe to run at any time and safe to run in CI: the overlay is rewritten
# from the filesystem on every run, so an overlay committed by accident cannot
# leak into a build that has no model to back it.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OVERLAY="Config/models-odr.yml"

# package directory (under Resources/Models) : ODR resource tag
MODELS=(
  "CLAPAudioEncoder.mlpackage:clap-audio"
  "CLAPTextEncoder.mlpackage:clap-text"
  "DemucsStems.mlpackage:demucs-stems"
)

present=()
absent=()
for entry in "${MODELS[@]}"; do
  dir="${entry%%:*}"
  if [[ -d "Resources/Models/$dir" ]]; then
    present+=("$entry")
  else
    absent+=("$dir")
  fi
done

{
  echo "# GENERATED by scripts/generate-project.sh — do not edit, and do not"
  echo "# commit: it is written from which model packages are on THIS machine."
  echo "#"
  echo "# A tag listed here is a package that exists; one that is missing is the"
  echo "# already-tested honest-absence path (§36.5, FR-SEM-6) — the decks play"
  echo "# the full mix with the stem faders disabled, and semantic search says it"
  echo "# is unavailable rather than pretending."
  if [[ ${#present[@]} -eq 0 ]]; then
    echo "#"
    echo "# No model packages on this machine, so this overlay is a no-op."
    echo "targets: {}"
  else
    echo "targets:"
    echo "  Tonearm:"
    echo "    sources:"
    for entry in "${present[@]}"; do
      dir="${entry%%:*}"
      tag="${entry##*:}"
      echo "      - path: Resources/Models/$dir"
      echo "        type: folder"
      echo "        buildPhase: resources"
      echo "        resourceTags:"
      echo "          - $tag"
    done
  fi
} > "$OVERLAY"

if [[ ${#present[@]} -gt 0 ]]; then
  echo "==> models: in this project — ${present[*]%%:*}"
fi
if [[ ${#absent[@]} -gt 0 ]]; then
  echo "==> models: absent, so their ODR tags are not in this project — ${absent[*]}"
  echo "    Run 'make models' to fetch the packages pinned in Config/models.lock."
  echo "    Demucs is not pinned there: convert it with tools/demucs-coreml/."
fi

xcodegen generate
